[package]
name = "sink"
version = "0.1.0"
authors = ["Blobfishman <lpkre@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
csv = "1.1.3"
chrono = "0.4.11"
